stages:
  - build
  - test
  - sonarqube


build:
  stage: build
  image: node:18
  script:
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/


test:
  stage: test
  image: node:18
  script:
    
    - npm test
  allow_failure: false


sonarqube-check:
  stage: sonarqube
  image: sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_HOST_URL: "${sonar_host_url}"      
    SONAR_LOGIN: "$SONAR_TOKEN"                            
  
  script:
  - >
    sonar-scanner
    -Dsonar.projectKey=WAE-SDA-SoSe2025---Gruppe-3
    -Dsonar.sources=.
    -Dsonar.host.url=$SONAR_HOST_URL
    -Dsonar.login=$SONAR_TOKEN
  only:
    - main 